package com.xanticious.androidgames.controller.games.pentomino

import com.xanticious.androidgames.model.games.pentomino.BoardSize
import com.xanticious.androidgames.model.games.pentomino.PentominoPiece
import com.xanticious.androidgames.model.games.pentomino.PentominoState
import com.xanticious.androidgames.model.games.puzzle.GridPos

/**
 * Pure Pentomino rules: piece geometry, placement validation, and solve check.
 * No Android or Compose imports — the entire rule set is JVM unit-testable.
 *
 * Piece orientations are generated by successive 90° rotations and an optional
 * horizontal reflection, then deduplicated. The canonical shape for each piece is
 * the normalized (min row = 0, min col = 0, lexicographically sorted) cell list.
 */
class PentominoController {

    /** Canonical (normalized) cell offsets for each of the twelve free pentominoes. */
    private val canonicalShapes: Map<PentominoPiece, List<GridPos>> = mapOf(
        // .XX / XX. / .X.
        PentominoPiece.F to cells(0,1, 0,2, 1,0, 1,1, 2,1),
        // XXXXX
        PentominoPiece.I to cells(0,0, 0,1, 0,2, 0,3, 0,4),
        // X. / X. / X. / XX
        PentominoPiece.L to cells(0,0, 1,0, 2,0, 3,0, 3,1),
        // .X / XX / X. / X.
        PentominoPiece.N to cells(0,1, 1,0, 1,1, 2,0, 3,0),
        // XX / XX / X.
        PentominoPiece.P to cells(0,0, 0,1, 1,0, 1,1, 2,0),
        // XXX / .X. / .X.
        PentominoPiece.T to cells(0,0, 0,1, 0,2, 1,1, 2,1),
        // X.X / XXX
        PentominoPiece.U to cells(0,0, 0,2, 1,0, 1,1, 1,2),
        // X.. / X.. / XXX
        PentominoPiece.V to cells(0,0, 1,0, 2,0, 2,1, 2,2),
        // X.. / XX. / .XX
        PentominoPiece.W to cells(0,0, 1,0, 1,1, 2,1, 2,2),
        // .X. / XXX / .X.
        PentominoPiece.X to cells(0,1, 1,0, 1,1, 1,2, 2,1),
        // .X / XX / .X / .X
        PentominoPiece.Y to cells(0,1, 1,0, 1,1, 2,1, 3,1),
        // XX. / .X. / .XX
        PentominoPiece.Z to cells(0,0, 0,1, 1,1, 2,1, 2,2)
    )

    val boardSizes: List<BoardSize> = BoardSize.entries

    // -------------------------------------------------------------------------
    // Geometry helpers
    // -------------------------------------------------------------------------

    /** Shift cells so that min row = 0 and min col = 0, then sort lexicographically. */
    internal fun normalize(cells: List<GridPos>): List<GridPos> {
        val minRow = cells.minOf { it.row }
        val minCol = cells.minOf { it.col }
        return cells.map { GridPos(it.row - minRow, it.col - minCol) }
            .sortedWith(compareBy({ it.row }, { it.col }))
    }

    /** Rotate cells 90° clockwise: (r, c) → (c, −r), then normalize. */
    internal fun rotate90(cells: List<GridPos>): List<GridPos> =
        normalize(cells.map { GridPos(it.col, -it.row) })

    /** Reflect cells horizontally: (r, c) → (r, −c), then normalize. */
    private fun reflect(cells: List<GridPos>): List<GridPos> =
        normalize(cells.map { GridPos(it.row, -it.col) })

    // -------------------------------------------------------------------------
    // Orientation enumeration
    // -------------------------------------------------------------------------

    /**
     * Returns all geometrically distinct orientations of [piece].
     * Always includes the 4 rotations; when [allowFlip] is true the 4 rotations
     * of the reflected shape are appended. Symmetrical pieces yield fewer entries
     * (e.g. X has 1, I has 2, F has 8 when flips allowed).
     */
    fun orientations(piece: PentominoPiece, allowFlip: Boolean): List<List<GridPos>> {
        val base = normalize(canonicalShapes.getValue(piece))
        val candidates = mutableListOf<List<GridPos>>()

        var current = base
        repeat(4) {
            candidates += current
            current = rotate90(current)
        }
        if (allowFlip) {
            var flipped = reflect(base)
            repeat(4) {
                candidates += flipped
                flipped = rotate90(flipped)
            }
        }

        val unique = mutableListOf<List<GridPos>>()
        for (candidate in candidates) {
            val norm = normalize(candidate)
            if (unique.none { it == norm }) unique += norm
        }
        return unique
    }

    // -------------------------------------------------------------------------
    // Placement rules
    // -------------------------------------------------------------------------

    /**
     * Returns true if placing [orientation] with its bounding-box origin at
     * [anchor] is legal: all five cells fall within the board and none overlap
     * an already-placed piece.
     */
    fun canPlace(state: PentominoState, orientation: List<GridPos>, anchor: GridPos): Boolean {
        val rows = state.boardSize.rows
        val cols = state.boardSize.cols
        val occupied = state.cellMap
        return orientation.all { offset ->
            val r = anchor.row + offset.row
            val c = anchor.col + offset.col
            r in 0 until rows && c in 0 until cols && GridPos(r, c) !in occupied
        }
    }

    /**
     * Places [piece] using [orientation] anchored at [anchor] on the board.
     * Clears the selected piece and pushes the current placements onto the undo stack.
     * Caller must verify legality with [canPlace] first.
     */
    fun place(
        state: PentominoState,
        piece: PentominoPiece,
        orientation: List<GridPos>,
        anchor: GridPos
    ): PentominoState {
        val cells = orientation.map { GridPos(anchor.row + it.row, anchor.col + it.col) }
        return state.copy(
            placements = state.placements + (piece to cells),
            history = state.history + listOf(state.placements)
        )
    }

    /** Removes [piece] from the board (lifts it back to the tray). */
    fun remove(state: PentominoState, piece: PentominoPiece): PentominoState =
        state.copy(
            placements = state.placements - piece,
            history = state.history + listOf(state.placements)
        )

    /** Reverts the most recent placement or removal. */
    fun undo(state: PentominoState): PentominoState {
        val previous = state.history.lastOrNull() ?: return state
        return state.copy(
            placements = previous,
            history = state.history.dropLast(1)
        )
    }

    /**
     * Returns true when all twelve pieces are placed and every board cell is
     * covered exactly once (no overlaps means [cellMap] size == total cells).
     */
    fun isSolved(state: PentominoState): Boolean {
        if (state.placements.size != PentominoPiece.entries.size) return false
        val totalCells = state.boardSize.rows * state.boardSize.cols
        val covered = state.placements.values.flatten().toSet()
        if (covered.size != totalCells) return false
        return covered.all {
            it.row in 0 until state.boardSize.rows && it.col in 0 until state.boardSize.cols
        }
    }

    /** Returns a fresh empty board for the given settings. */
    fun newGame(boardSize: BoardSize, allowFlip: Boolean): PentominoState =
        PentominoState(boardSize = boardSize, allowFlip = allowFlip)

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    private fun cells(vararg coords: Int): List<GridPos> {
        require(coords.size % 2 == 0)
        return coords.toList().chunked(2).map { (r, c) -> GridPos(r, c) }
    }
}
