package com.xanticious.androidgames.model

object GameCatalog {
    val allGames: List<GameDefinition> = listOf(
<<<<<<< HEAD
        game("age-of-empires-lite", "Age of Empires Lite", GameCategory.RTS),
        game("anagrams", "Anagrams", GameCategory.WORD, released = true, selfConfigured = true),
        game("anagrams-arcade", "Anagrams (Arcade)", GameCategory.WORD, released = true, selfConfigured = true),
=======
        game("age-of-empires-lite", "Age of Empires Lite", GameCategory.RTS, released = true),
        game("anagrams", "Anagrams", GameCategory.WORD),
        game("anagrams-arcade", "Anagrams (Arcade)", GameCategory.WORD),
        game("anomaly-defense", "Anomaly Defense", GameCategory.TOWER_DEFENSE, released = true),
>>>>>>> origin/main
        game("asteroids", "Asteroids", GameCategory.ACTION, released = true, selfConfigured = true),
        game("backgammon", "Backgammon", GameCategory.BOARD),
        game("base-defense", "Base Defense", GameCategory.TOWER_DEFENSE, released = true),
        game("battleships", "Battleships", GameCategory.STRATEGY, released = true),
        game("boggle", "Boggle", GameCategory.WORD),
        game("bomber-grid", "Bomber Grid", GameCategory.ACTION, released = true),
        game("brick-breaker", "Brick Breaker", GameCategory.ACTION, released = true),
        game("brick-breaker-arcade", "Brick Breaker (Arcade)", GameCategory.ACTION, released = true),
        game("brick-breaker-cannon", "Brick Breaker (Cannon)", GameCategory.ACTION, released = true),
        game("brick-breaker-cannon-arcade", "Brick Breaker (Cannon Arcade)", GameCategory.ACTION, released = true),
<<<<<<< HEAD
        game("backgammon", "Backgammon", GameCategory.BOARD),
        game("battleships", "Battleships", GameCategory.STRATEGY),
        game("boggle", "Boggle", GameCategory.WORD, released = true, selfConfigured = true),
=======
>>>>>>> origin/main
        game("bubbles-pop", "Bubbles Pop", GameCategory.ACTION, released = true),
        game("bubbles-pop-arcade", "Bubbles Pop (Arcade)", GameCategory.ACTION, released = true),
        game("bubbles-pop-snake-arcade", "Bubbles Pop Snake (Arcade)", GameCategory.ACTION, released = true),
        game("carcassonne-lite", "Carcassonne Lite", GameCategory.BOARD),
        game("checkers", "Checkers", GameCategory.STRATEGY, released = true),
        game("chess", "Chess", GameCategory.STRATEGY),
        game("chinese-checkers", "Chinese Checkers", GameCategory.BOARD, released = true),
        game("city-merge-idle", "City Merge Idle", GameCategory.IDLE),
        game("connect-four", "Connect Four", GameCategory.STRATEGY, released = true),
        game("cribbage", "Cribbage", GameCategory.CARD, released = true),
        game("deck-builder-fleet", "Deck Builder Fleet", GameCategory.CARD, released = true),
        game("deck-builder-superhero", "Deck Builder Superhero", GameCategory.CARD, released = true),
        game("dominoes", "Dominoes", GameCategory.BOARD, released = true),
        game("dominosa", "Dominosa", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("dot-art", "Dot Art", GameCategory.EXPLORATION_CREATIVE, released = true, selfConfigured = true),
        game("draughts-variants", "Draughts Variants", GameCategory.STRATEGY),
        game("drift-racer", "Drift Racer", GameCategory.ACTION, released = true),
        game("empire-skirmish", "Empire Skirmish", GameCategory.RTS, released = true),
        game("endless-runner", "Endless Runner", GameCategory.ACTION, released = true),
        game("falling-blocks", "Falling Blocks", GameCategory.PUZZLE),
        game("falling-blocks-arcade", "Falling Blocks (Arcade)", GameCategory.PUZZLE),
        game("find-pairs", "Find Pairs", GameCategory.SEARCH),
<<<<<<< HEAD
        game("flood", "Flood", GameCategory.PUZZLE),
        game("gomoku", "Gomoku", GameCategory.STRATEGY),
        game("melody-master", "Melody Master", GameCategory.RHYTHM),
        game("morse-code", "Morse Code", GameCategory.RHYTHM),
        game("morse-decoder", "Morse Decoder", GameCategory.RHYTHM),
        game("word-slices", "Word Slices", GameCategory.WORD, released = true, selfConfigured = true),
        game("hearts", "Hearts", GameCategory.CARD),
        game("hex", "Hex", GameCategory.STRATEGY),
        game("hidden-objects", "Hidden Objects", GameCategory.SEARCH),
=======
        game("flash-cards", "Flash Cards", GameCategory.EDUCATIONAL, released = true, selfConfigured = true),
        game("flood", "Flood", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("gomoku", "Gomoku", GameCategory.STRATEGY, released = true),
        game("hearts", "Hearts", GameCategory.CARD, released = true),
        game("helicopter-dogfight", "Helicopter Dogfight", GameCategory.ACTION, released = true),
        game("hex", "Hex", GameCategory.STRATEGY, released = true),
        game("hidden-object", "Hidden Object", GameCategory.SEARCH, released = true, selfConfigured = true),
        game("hidden-objects", "Hidden Objects", GameCategory.SEARCH, released = true, selfConfigured = true),
>>>>>>> origin/main
        game("hole-swallowing-game", "Hole Swallowing Game", GameCategory.ACTION, released = true),
        game("idle-animal-merge", "Idle Animal Merge", GameCategory.IDLE, released = true, selfConfigured = true),
        game("idle-bounce", "Idle Bounce", GameCategory.IDLE, released = true, selfConfigured = true),
        game("idle-city-builder", "Idle City Builder", GameCategory.IDLE),
        game("idle-combat-training", "Idle Combat Training", GameCategory.IDLE, released = true, selfConfigured = true),
        game("idle-factory", "Idle Factory", GameCategory.IDLE),
        game("idle-farm", "Idle Farm", GameCategory.IDLE),
<<<<<<< HEAD
        game("jigsaw", "Jigsaw", GameCategory.PUZZLE),
        game("letter-drop", "Letter Drop", GameCategory.WORD, released = true, selfConfigured = true),
        game("light-up", "Light Up", GameCategory.PUZZLE),
        game("logic-grid", "Logic Grid", GameCategory.PUZZLE),
        game("love-letter", "Love Letter", GameCategory.BOARD),
=======
        game("idle-farmers", "Idle Farmers", GameCategory.IDLE, released = true, selfConfigured = true),
        game("idle-genetic-algorithm", "Idle Genetic Algorithm", GameCategory.IDLE, released = true, selfConfigured = true),
        game("idle-lab", "Idle Lab", GameCategory.IDLE),
        game("idle-player-piano", "Idle Player Piano", GameCategory.IDLE, released = true, selfConfigured = true),
        game("jigsaw", "Jigsaw", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("letter-drop", "Letter Drop", GameCategory.WORD),
        game("light-up", "Light Up", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("logic-grid", "Logic Grid", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("love-letter", "Love Letter", GameCategory.CARD, released = true),
        game("ludo", "Ludo", GameCategory.BOARD),
>>>>>>> origin/main
        game("mahjong-solitaire", "Mahjong Solitaire", GameCategory.PUZZLE),
        game("mastermind", "Mastermind", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("match-three", "Match Three", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("match-three-arcade", "Match Three (Arcade)", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("math-quiz", "Math Quiz", GameCategory.EDUCATIONAL, released = true, selfConfigured = true),
        game("mazes", "Mazes", GameCategory.SEARCH),
        game("melody-master", "Melody Master", GameCategory.RHYTHM, released = true, selfConfigured = true),
        game("memory", "Memory", GameCategory.MEMORY, released = true),
        game("memory-lanes", "Memory Lanes", GameCategory.MEMORY, released = true, selfConfigured = true),
        game("minesweeper", "Mine Sweeper", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("missile-command", "Missile Command", GameCategory.ACTION, released = true),
        game("morse-code", "Morse Code", GameCategory.RHYTHM, released = true, selfConfigured = true),
        game("morse-decoder", "Morse Decoder", GameCategory.RHYTHM, released = true, selfConfigured = true),
        game("nonogram", "Nonogram", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("numberlink", "Numberlink", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("othello", "Othello", GameCategory.STRATEGY),
        game("overcooked-lite", "Overcooked Lite", GameCategory.QUEUE_STRATEGY_ACTION),
        game("pair-collector", "Pair Collector", GameCategory.SEARCH, released = true, selfConfigured = true),
        game("pathfinder", "Pathfinder", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("peg-solitaire", "Peg Solitaire", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("pentomino", "Pentomino", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("pipes", "Pipes", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("pirate-treasure-maze", "Pirate Treasure Maze", GameCategory.SEARCH, released = true, selfConfigured = true),
        game("planet-explorer", "Planet Explorer", GameCategory.EXPLORATION_CREATIVE, released = true, selfConfigured = true),
        game("poker", "Poker", GameCategory.CARD, released = true),
        game("pong", "Pong", GameCategory.ACTION, released = true),
        game("qix", "Qix", GameCategory.ACTION, released = true),
        game("qwirkle-lite", "Qwirkle Lite", GameCategory.BOARD),
<<<<<<< HEAD
        game("randomized-dice-td", "Randomized Dice TD", GameCategory.TOWER_DEFENSE),
        game("reversi", "Reversi", GameCategory.STRATEGY),
        game("helicopter-dogfight", "Helicopter Dogfight", GameCategory.ACTION, released = true),
        game("pirate-treasure-maze", "Pirate Treasure Maze", GameCategory.SEARCH),
        game("scrabble", "Scrabble", GameCategory.WORD, released = true, selfConfigured = true),
        game("scrabble-single-player-challenge", "Scrabble Single Player Challenge", GameCategory.WORD, released = true, selfConfigured = true),
        game("pair-collector", "Pair Collector", GameCategory.SEARCH),
=======
        game("randomized-dice-td", "Randomized Dice TD", GameCategory.TOWER_DEFENSE, released = true),
        game("reaction-speed", "Reaction Speed", GameCategory.RHYTHM),
        game("resource-frontier", "Resource Frontier", GameCategory.RTS),
        game("reversi", "Reversi", GameCategory.STRATEGY, released = true),
        game("rogue-caverns", "Rogue Caverns", GameCategory.EXPLORATION_CREATIVE, released = true),
        game("scrabble", "Scrabble", GameCategory.WORD),
        game("scrabble-single-player-challenge", "Scrabble Single Player Challenge", GameCategory.WORD),
>>>>>>> origin/main
        game("shogi-lite", "Shogi Lite", GameCategory.STRATEGY),
        game("sim-city-blocks", "Sim City Blocks", GameCategory.EXPLORATION_CREATIVE, released = true, selfConfigured = true),
        game("skyscrapers", "Skyscrapers", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("sliding-puzzle", "Sliding Puzzle", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("snakes-2d", "Snakes 2D", GameCategory.ACTION, released = true),
        game("sokoban", "Sokoban", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("solitaire-clock-timed", "Solitaire (Clock Timed)", GameCategory.CARD, released = true),
        game("solitaire-freecell", "Solitaire (FreeCell)", GameCategory.CARD, released = true),
        game("solitaire-klondike", "Solitaire (Klondike)", GameCategory.CARD, released = true),
        game("solitaire-pyramid", "Solitaire (Pyramid)", GameCategory.CARD, released = true),
        game("solitaire-tripeaks", "Solitaire (TriPeaks)", GameCategory.CARD, released = true),
        game("solitaire-tripeaks-timed", "Solitaire (TriPeaks Timed)", GameCategory.CARD, released = true),
        game("space-defender", "Space Defender", GameCategory.ACTION, released = true),
        game("spades", "Spades", GameCategory.CARD, released = true),
        game("splendor", "Splendor", GameCategory.BOARD),
        game("star-miner", "Star Miner", GameCategory.EXPLORATION_CREATIVE),
        game("sudoku-colors", "Sudoku Colors", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("tafl-lite", "Tafl Lite", GameCategory.STRATEGY),
        game("tap-rhythm", "Tap Rhythm", GameCategory.RHYTHM, released = true, selfConfigured = true),
        game("tic-tac-toe", "Tic Tac Toe", GameCategory.STRATEGY, released = true),
        game("trans-america", "Trans-America", GameCategory.BOARD),
        game("treasure-mapper", "Treasure Mapper", GameCategory.SEARCH, released = true, selfConfigured = true),
        game("trivia-blitz", "Trivia Blitz", GameCategory.EDUCATIONAL),
<<<<<<< HEAD
        game("twenty-forty-eight", "2048", GameCategory.PUZZLE),
        game("word-chain", "Word Chain", GameCategory.WORD, released = true, selfConfigured = true),
        game("word-ladder", "Word Ladder", GameCategory.WORD, released = true, selfConfigured = true),
        game("word-search", "Word Search", GameCategory.SEARCH, released = true, selfConfigured = true),
        game("wordle", "Wordle", GameCategory.WORD, released = true, selfConfigured = true),
        game("hidden-object", "Hidden Object", GameCategory.SEARCH),
        game("yahtzee", "Yahtzee", GameCategory.DICE),
=======
        game("twenty-forty-eight", "2048", GameCategory.PUZZLE, released = true, selfConfigured = true),
        game("typing-sprint", "Typing Sprint", GameCategory.EDUCATIONAL),
        game("word-chain", "Word Chain", GameCategory.WORD),
        game("word-ladder", "Word Ladder", GameCategory.WORD),
        game("word-search", "Word Search", GameCategory.SEARCH),
        game("word-slices", "Word Slices", GameCategory.WORD),
        game("wordle", "Wordle", GameCategory.WORD),
        game("yahtzee", "Yahtzee", GameCategory.DICE, released = true),
>>>>>>> origin/main
        game("yatzy", "Yatzy", GameCategory.DICE),
        game("zen-garden", "Zen Garden", GameCategory.EXPLORATION_CREATIVE),
<<<<<<< HEAD
        game("pathfinder", "Pathfinder", GameCategory.PUZZLE),
        game("bomber-grid", "Bomber Grid", GameCategory.ACTION, released = true),
        game("rogue-caverns", "Rogue Caverns", GameCategory.EXPLORATION_CREATIVE),
        game("deck-builder-superhero", "Deck Builder Superhero", GameCategory.CARD),
        game("deck-builder-fleet", "Deck Builder Fleet", GameCategory.CARD),
        game("ludo", "Ludo", GameCategory.BOARD),
        game("reaction-speed", "Reaction Speed", GameCategory.RHYTHM),
        game("typing-sprint", "Typing Sprint", GameCategory.EDUCATIONAL, released = true, selfConfigured = true)
=======
        game("zilch", "Zilch", GameCategory.DICE, released = true)
>>>>>>> origin/main
    )

    private fun game(
        id: String,
        name: String,
        category: GameCategory,
        released: Boolean = false,
        selfConfigured: Boolean = false
    ): GameDefinition =
        GameDefinition(id = id, name = name, category = category, released = released, selfConfigured = selfConfigured)
}
